CRITICAL - 2024-08-12 06:12:07 --> ErrorException: Trying to access array offset on value of type null
[Method: GET, Route: checkout]
in APPPATH\Controllers\CheckoutController.php on line 19.
 1 APPPATH\Controllers\CheckoutController.php(19): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'C:\\Users\\HP\\OneDrive\\Documents\\GitHub\\learnxa\\app\\Controllers\\CheckoutController.php', 19)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\CheckoutController->index()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CheckoutController))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\Users\\HP\\OneDrive\\Documents\\GitHub\\learnxa\\public\\index.php')
CRITICAL - 2024-08-12 06:12:09 --> ErrorException: Trying to access array offset on value of type null
[Method: GET, Route: checkout]
in APPPATH\Controllers\CheckoutController.php on line 19.
 1 APPPATH\Controllers\CheckoutController.php(19): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'C:\\Users\\HP\\OneDrive\\Documents\\GitHub\\learnxa\\app\\Controllers\\CheckoutController.php', 19)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\CheckoutController->index()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CheckoutController))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\Users\\HP\\OneDrive\\Documents\\GitHub\\learnxa\\public\\index.php')
CRITICAL - 2024-08-12 06:12:13 --> ErrorException: Trying to access array offset on value of type null
[Method: GET, Route: checkout]
in APPPATH\Controllers\CheckoutController.php on line 19.
 1 APPPATH\Controllers\CheckoutController.php(19): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'C:\\Users\\HP\\OneDrive\\Documents\\GitHub\\learnxa\\app\\Controllers\\CheckoutController.php', 19)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\CheckoutController->index()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CheckoutController))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\Users\\HP\\OneDrive\\Documents\\GitHub\\learnxa\\public\\index.php')
CRITICAL - 2024-08-12 06:12:16 --> ErrorException: Trying to access array offset on value of type null
[Method: GET, Route: checkout]
in APPPATH\Controllers\CheckoutController.php on line 19.
 1 APPPATH\Controllers\CheckoutController.php(19): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'C:\\Users\\HP\\OneDrive\\Documents\\GitHub\\learnxa\\app\\Controllers\\CheckoutController.php', 19)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\CheckoutController->index()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CheckoutController))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\Users\\HP\\OneDrive\\Documents\\GitHub\\learnxa\\public\\index.php')
CRITICAL - 2024-08-12 06:12:17 --> ErrorException: Trying to access array offset on value of type null
[Method: GET, Route: checkout]
in APPPATH\Controllers\CheckoutController.php on line 19.
 1 APPPATH\Controllers\CheckoutController.php(19): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'C:\\Users\\HP\\OneDrive\\Documents\\GitHub\\learnxa\\app\\Controllers\\CheckoutController.php', 19)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\CheckoutController->index()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CheckoutController))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\Users\\HP\\OneDrive\\Documents\\GitHub\\learnxa\\public\\index.php')
CRITICAL - 2024-08-12 06:12:18 --> ErrorException: Trying to access array offset on value of type null
[Method: GET, Route: checkout]
in APPPATH\Controllers\CheckoutController.php on line 19.
 1 APPPATH\Controllers\CheckoutController.php(19): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'C:\\Users\\HP\\OneDrive\\Documents\\GitHub\\learnxa\\app\\Controllers\\CheckoutController.php', 19)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\CheckoutController->index()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CheckoutController))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\Users\\HP\\OneDrive\\Documents\\GitHub\\learnxa\\public\\index.php')
CRITICAL - 2024-08-12 06:12:19 --> ErrorException: Trying to access array offset on value of type null
[Method: GET, Route: checkout]
in APPPATH\Controllers\CheckoutController.php on line 19.
 1 APPPATH\Controllers\CheckoutController.php(19): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Trying to access array offset on value of type null', 'C:\\Users\\HP\\OneDrive\\Documents\\GitHub\\learnxa\\app\\Controllers\\CheckoutController.php', 19)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\CheckoutController->index()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CheckoutController))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\Users\\HP\\OneDrive\\Documents\\GitHub\\learnxa\\public\\index.php')
ERROR - 2024-08-12 18:31:27 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:186
Stack trace:
#0 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'learnxa', 3306, '', 0)
#1 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 /home/learnxac/learnxa/app/Models/CourseModel.php(42): CodeIgniter\BaseModel->findAll()
#7 /home/learnxac/learnxa/app/Controllers/CourseController.php(16): App\Models\CourseModel->getCourses()
#8 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(933): App\Controllers\CourseController->index()
#9 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CourseController))
#10 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 /home/learnxac/public_html/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:231
Stack trace:
#0 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#5 /home/learnxac/learnxa/app/Models/CourseModel.php(42): CodeIgniter\BaseModel->findAll()
#6 /home/learnxac/learnxa/app/Controllers/CourseController.php(16): App\Models\CourseModel->getCourses()
#7 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(933): App\Controllers\CourseController->index()
#8 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CourseController))
#9 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 /home/learnxac/public_html/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2024-08-12 18:31:27 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
[Method: GET, Route: courses]
in SYSTEMPATH/Database/BaseConnection.php on line 467.
 1 SYSTEMPATH/Database/BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `courses`', [], false)
 3 SYSTEMPATH/Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH/Models/CourseModel.php(42): CodeIgniter\BaseModel->findAll()
 6 APPPATH/Controllers/CourseController.php(16): App\Models\CourseModel->getCourses()
 7 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\CourseController->index()
 8 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CourseController))
 9 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH/Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-08-12 18:57:39 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:186
Stack trace:
#0 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'learnxa', 3306, '', 0)
#1 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 /home/learnxac/learnxa/app/Controllers/Pages.php(171): CodeIgniter\BaseModel->findAll()
#7 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(933): App\Controllers\Pages->createAndEditCourse()
#8 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pages))
#9 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 /home/learnxac/public_html/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:231
Stack trace:
#0 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#5 /home/learnxac/learnxa/app/Controllers/Pages.php(171): CodeIgniter\BaseModel->findAll()
#6 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(933): App\Controllers\Pages->createAndEditCourse()
#7 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pages))
#8 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 /home/learnxac/public_html/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2024-08-12 18:57:39 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
[Method: GET, Route: admin/course]
in SYSTEMPATH/Database/BaseConnection.php on line 467.
 1 SYSTEMPATH/Database/BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `topics`', [], false)
 3 SYSTEMPATH/Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH/Controllers/Pages.php(171): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Pages->createAndEditCourse()
 7 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pages))
 8 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH/Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-08-12 19:09:28 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'learnxac_learnxa'@'localhost' to database 'learnxac_learnxa' in /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:186
Stack trace:
#0 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(186): mysqli->real_connect('localhost', 'learnxac_learnx...', Object(SensitiveParameterValue), 'learnxac_learnx...', 3306, '', 0)
#1 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 /home/learnxac/learnxa/app/Controllers/Pages.php(171): CodeIgniter\BaseModel->findAll()
#7 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(933): App\Controllers\Pages->createAndEditCourse()
#8 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pages))
#9 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 /home/learnxac/public_html/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' to database '****' in /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:231
Stack trace:
#0 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#5 /home/learnxac/learnxa/app/Controllers/Pages.php(171): CodeIgniter\BaseModel->findAll()
#6 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(933): App\Controllers\Pages->createAndEditCourse()
#7 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pages))
#8 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 /home/learnxac/public_html/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2024-08-12 19:09:28 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' to database '****'
[Method: GET, Route: admin/course]
in SYSTEMPATH/Database/BaseConnection.php on line 467.
 1 SYSTEMPATH/Database/BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `topics`', [], false)
 3 SYSTEMPATH/Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH/Controllers/Pages.php(171): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Pages->createAndEditCourse()
 7 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pages))
 8 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH/Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-08-12 19:10:03 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'learnxac_learnxa'@'localhost' to database 'learnxac_learnxa' in /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:186
Stack trace:
#0 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(186): mysqli->real_connect('localhost', 'learnxac_learnx...', Object(SensitiveParameterValue), 'learnxac_learnx...', 3306, '', 0)
#1 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 /home/learnxac/learnxa/app/Controllers/Pages.php(171): CodeIgniter\BaseModel->findAll()
#7 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(933): App\Controllers\Pages->createAndEditCourse()
#8 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pages))
#9 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 /home/learnxac/public_html/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' to database '****' in /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:231
Stack trace:
#0 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#5 /home/learnxac/learnxa/app/Controllers/Pages.php(171): CodeIgniter\BaseModel->findAll()
#6 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(933): App\Controllers\Pages->createAndEditCourse()
#7 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pages))
#8 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 /home/learnxac/public_html/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2024-08-12 19:10:03 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' to database '****'
[Method: GET, Route: admin/course]
in SYSTEMPATH/Database/BaseConnection.php on line 467.
 1 SYSTEMPATH/Database/BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `topics`', [], false)
 3 SYSTEMPATH/Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH/Controllers/Pages.php(171): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Pages->createAndEditCourse()
 7 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pages))
 8 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH/Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-08-12 19:20:23 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'learnxac_learnxa'@'localhost' to database 'learnxac_learnxa' in /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:186
Stack trace:
#0 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(186): mysqli->real_connect('localhost', 'learnxac_learnx...', Object(SensitiveParameterValue), 'learnxac_learnx...', 3306, '', 0)
#1 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 /home/learnxac/learnxa/app/Controllers/Pages.php(171): CodeIgniter\BaseModel->findAll()
#7 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(933): App\Controllers\Pages->createAndEditCourse()
#8 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pages))
#9 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 /home/learnxac/public_html/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' to database '****' in /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:231
Stack trace:
#0 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#5 /home/learnxac/learnxa/app/Controllers/Pages.php(171): CodeIgniter\BaseModel->findAll()
#6 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(933): App\Controllers\Pages->createAndEditCourse()
#7 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pages))
#8 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 /home/learnxac/public_html/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2024-08-12 19:20:23 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' to database '****'
[Method: GET, Route: admin/course]
in SYSTEMPATH/Database/BaseConnection.php on line 467.
 1 SYSTEMPATH/Database/BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `topics`', [], false)
 3 SYSTEMPATH/Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH/Controllers/Pages.php(171): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Pages->createAndEditCourse()
 7 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pages))
 8 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH/Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-08-12 19:20:49 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'learnxac_learnxa'@'localhost' to database 'learnxac_learnxa' in /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:186
Stack trace:
#0 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(186): mysqli->real_connect('localhost', 'learnxac_learnx...', Object(SensitiveParameterValue), 'learnxac_learnx...', 3306, '', 0)
#1 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 /home/learnxac/learnxa/app/Models/CourseModel.php(42): CodeIgniter\BaseModel->findAll()
#7 /home/learnxac/learnxa/app/Controllers/CourseController.php(16): App\Models\CourseModel->getCourses()
#8 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(933): App\Controllers\CourseController->index()
#9 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CourseController))
#10 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 /home/learnxac/public_html/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' to database '****' in /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:231
Stack trace:
#0 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#5 /home/learnxac/learnxa/app/Models/CourseModel.php(42): CodeIgniter\BaseModel->findAll()
#6 /home/learnxac/learnxa/app/Controllers/CourseController.php(16): App\Models\CourseModel->getCourses()
#7 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(933): App\Controllers\CourseController->index()
#8 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CourseController))
#9 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 /home/learnxac/public_html/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2024-08-12 19:20:49 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' to database '****'
[Method: GET, Route: courses]
in SYSTEMPATH/Database/BaseConnection.php on line 467.
 1 SYSTEMPATH/Database/BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `courses`', [], false)
 3 SYSTEMPATH/Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH/Models/CourseModel.php(42): CodeIgniter\BaseModel->findAll()
 6 APPPATH/Controllers/CourseController.php(16): App\Models\CourseModel->getCourses()
 7 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\CourseController->index()
 8 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CourseController))
 9 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH/Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-08-12 19:29:45 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'learnxac_learnxa'@'localhost' to database 'learnxac_learnxa' in /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:186
Stack trace:
#0 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(186): mysqli->real_connect('localhost', 'learnxac_learnx...', Object(SensitiveParameterValue), 'learnxac_learnx...', 3306, '', 0)
#1 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#6 /home/learnxac/learnxa/app/Models/CourseModel.php(42): CodeIgniter\BaseModel->findAll()
#7 /home/learnxac/learnxa/app/Controllers/CourseController.php(16): App\Models\CourseModel->getCourses()
#8 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(933): App\Controllers\CourseController->index()
#9 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CourseController))
#10 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 /home/learnxac/public_html/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' to database '****' in /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:231
Stack trace:
#0 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
#5 /home/learnxac/learnxa/app/Models/CourseModel.php(42): CodeIgniter\BaseModel->findAll()
#6 /home/learnxac/learnxa/app/Controllers/CourseController.php(16): App\Models\CourseModel->getCourses()
#7 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(933): App\Controllers\CourseController->index()
#8 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CourseController))
#9 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 /home/learnxac/public_html/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
CRITICAL - 2024-08-12 19:29:45 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' to database '****'
[Method: GET, Route: courses]
in SYSTEMPATH/Database/BaseConnection.php on line 467.
 1 SYSTEMPATH/Database/BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `courses`', [], false)
 3 SYSTEMPATH/Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(676): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH/Models/CourseModel.php(42): CodeIgniter\BaseModel->findAll()
 6 APPPATH/Controllers/CourseController.php(16): App\Models\CourseModel->getCourses()
 7 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\CourseController->index()
 8 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\CourseController))
 9 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH/Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-08-12 19:41:54 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'learnxac_learnxa'@'localhost' to database 'learnxac_learnxa' in /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:186
Stack trace:
#0 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(186): mysqli->real_connect('localhost', 'learnxac_learnx...', Object(SensitiveParameterValue), 'learnxac_learnx...', 3306, '', 0)
#1 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/BaseModel.php(714): CodeIgniter\Model->doFirst()
#6 /home/learnxac/learnxa/app/Controllers/AuthReg.php(204): CodeIgniter\BaseModel->first()
#7 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(933): App\Controllers\AuthReg->processInvoice()
#8 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthReg))
#9 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 /home/learnxac/public_html/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' to database '****' in /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:231
Stack trace:
#0 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#4 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/BaseModel.php(714): CodeIgniter\Model->doFirst()
#5 /home/learnxac/learnxa/app/Controllers/AuthReg.php(204): CodeIgniter\BaseModel->first()
#6 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(933): App\Controllers\AuthReg->processInvoice()
#7 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthReg))
#8 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 /home/learnxac/public_html/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2024-08-12 19:41:54 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' to database '****'
[Method: POST, Route: invoice-process]
in SYSTEMPATH/Database/BaseConnection.php on line 467.
 1 SYSTEMPATH/Database/BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `email` = :email:
 LIMIT 1', [...], false)
 3 SYSTEMPATH/Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(714): CodeIgniter\Model->doFirst()
 5 APPPATH/Controllers/AuthReg.php(204): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\AuthReg->processInvoice()
 7 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthReg))
 8 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH/Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-08-12 19:47:10 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'learnxac_learnxa'@'localhost' to database 'learnxac_learnxa' in /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:186
Stack trace:
#0 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(186): mysqli->real_connect('localhost', 'learnxac_learnx...', Object(SensitiveParameterValue), 'learnxac_learnx...', 3306, '', 0)
#1 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/BaseModel.php(714): CodeIgniter\Model->doFirst()
#6 /home/learnxac/learnxa/app/Controllers/AuthReg.php(204): CodeIgniter\BaseModel->first()
#7 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(933): App\Controllers\AuthReg->processInvoice()
#8 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthReg))
#9 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 /home/learnxac/public_html/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' to database '****' in /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:231
Stack trace:
#0 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#4 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/BaseModel.php(714): CodeIgniter\Model->doFirst()
#5 /home/learnxac/learnxa/app/Controllers/AuthReg.php(204): CodeIgniter\BaseModel->first()
#6 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(933): App\Controllers\AuthReg->processInvoice()
#7 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthReg))
#8 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 /home/learnxac/public_html/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2024-08-12 19:47:10 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' to database '****'
[Method: POST, Route: invoice-process]
in SYSTEMPATH/Database/BaseConnection.php on line 467.
 1 SYSTEMPATH/Database/BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `email` = :email:
 LIMIT 1', [...], false)
 3 SYSTEMPATH/Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(714): CodeIgniter\Model->doFirst()
 5 APPPATH/Controllers/AuthReg.php(204): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\AuthReg->processInvoice()
 7 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthReg))
 8 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH/Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-08-12 19:48:25 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'learnxac_learnxa'@'localhost' to database 'learnxac_learnxa' in /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:186
Stack trace:
#0 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(186): mysqli->real_connect('localhost', 'learnxac_learnx...', Object(SensitiveParameterValue), 'learnxac_learnx...', 3306, '', 0)
#1 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/BaseModel.php(714): CodeIgniter\Model->doFirst()
#6 /home/learnxac/learnxa/app/Controllers/AuthReg.php(204): CodeIgniter\BaseModel->first()
#7 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(933): App\Controllers\AuthReg->processInvoice()
#8 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthReg))
#9 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 /home/learnxac/public_html/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' to database '****' in /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:231
Stack trace:
#0 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#4 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/BaseModel.php(714): CodeIgniter\Model->doFirst()
#5 /home/learnxac/learnxa/app/Controllers/AuthReg.php(204): CodeIgniter\BaseModel->first()
#6 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(933): App\Controllers\AuthReg->processInvoice()
#7 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthReg))
#8 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 /home/learnxac/public_html/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2024-08-12 19:48:25 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' to database '****'
[Method: POST, Route: invoice-process]
in SYSTEMPATH/Database/BaseConnection.php on line 467.
 1 SYSTEMPATH/Database/BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `email` = :email:
 LIMIT 1', [...], false)
 3 SYSTEMPATH/Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(714): CodeIgniter\Model->doFirst()
 5 APPPATH/Controllers/AuthReg.php(204): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\AuthReg->processInvoice()
 7 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthReg))
 8 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH/Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-08-12 19:54:34 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'learnxac_learnxa'@'localhost' to database 'learnxac_learnxa' in /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:187
Stack trace:
#0 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(187): mysqli->real_connect('localhost', 'learnxac_learnx...', 'e-learnxa@2024', 'learnxac_learnx...', 3306, '', 0)
#1 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/BaseModel.php(714): CodeIgniter\Model->doFirst()
#6 /home/learnxac/learnxa/app/Controllers/AuthReg.php(204): CodeIgniter\BaseModel->first()
#7 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(933): App\Controllers\AuthReg->processInvoice()
#8 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthReg))
#9 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 /home/learnxac/public_html/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' to database '****' in /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:231
Stack trace:
#0 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#4 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/BaseModel.php(714): CodeIgniter\Model->doFirst()
#5 /home/learnxac/learnxa/app/Controllers/AuthReg.php(204): CodeIgniter\BaseModel->first()
#6 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(933): App\Controllers\AuthReg->processInvoice()
#7 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthReg))
#8 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 /home/learnxac/public_html/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2024-08-12 19:54:34 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' to database '****'
[Method: POST, Route: invoice-process]
in SYSTEMPATH/Database/BaseConnection.php on line 467.
 1 SYSTEMPATH/Database/BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `email` = :email:
 LIMIT 1', [...], false)
 3 SYSTEMPATH/Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(714): CodeIgniter\Model->doFirst()
 5 APPPATH/Controllers/AuthReg.php(204): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\AuthReg->processInvoice()
 7 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthReg))
 8 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH/Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-08-12 19:54:42 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'learnxac_learnxa'@'localhost' to database 'learnxac_learnxa' in /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:187
Stack trace:
#0 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(187): mysqli->real_connect('localhost', 'learnxac_learnx...', 'e-learnxa@2024', 'learnxac_learnx...', 3306, '', 0)
#1 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/BaseModel.php(714): CodeIgniter\Model->doFirst()
#6 /home/learnxac/learnxa/app/Controllers/AuthReg.php(204): CodeIgniter\BaseModel->first()
#7 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(933): App\Controllers\AuthReg->processInvoice()
#8 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthReg))
#9 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 /home/learnxac/public_html/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' to database '****' in /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:231
Stack trace:
#0 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#4 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/BaseModel.php(714): CodeIgniter\Model->doFirst()
#5 /home/learnxac/learnxa/app/Controllers/AuthReg.php(204): CodeIgniter\BaseModel->first()
#6 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(933): App\Controllers\AuthReg->processInvoice()
#7 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthReg))
#8 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 /home/learnxac/public_html/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2024-08-12 19:54:42 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' to database '****'
[Method: POST, Route: invoice-process]
in SYSTEMPATH/Database/BaseConnection.php on line 467.
 1 SYSTEMPATH/Database/BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `email` = :email:
 LIMIT 1', [...], false)
 3 SYSTEMPATH/Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(714): CodeIgniter\Model->doFirst()
 5 APPPATH/Controllers/AuthReg.php(204): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\AuthReg->processInvoice()
 7 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthReg))
 8 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH/Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-08-12 20:20:21 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'learnxac_LearnXa'@'localhost' to database 'learnxac_learnxa' in /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:186
Stack trace:
#0 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(186): mysqli->real_connect('localhost', 'learnxac_LearnX...', Object(SensitiveParameterValue), 'learnxac_learnx...', 3306, '', 0)
#1 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/BaseModel.php(714): CodeIgniter\Model->doFirst()
#6 /home/learnxac/learnxa/app/Controllers/AuthReg.php(204): CodeIgniter\BaseModel->first()
#7 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(933): App\Controllers\AuthReg->processInvoice()
#8 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthReg))
#9 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 /home/learnxac/public_html/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' to database 'learnxac_learnxa' in /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:231
Stack trace:
#0 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#4 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/BaseModel.php(714): CodeIgniter\Model->doFirst()
#5 /home/learnxac/learnxa/app/Controllers/AuthReg.php(204): CodeIgniter\BaseModel->first()
#6 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(933): App\Controllers\AuthReg->processInvoice()
#7 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthReg))
#8 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 /home/learnxac/public_html/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2024-08-12 20:20:21 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' to database 'learnxac_learnxa'
[Method: POST, Route: invoice-process]
in SYSTEMPATH/Database/BaseConnection.php on line 467.
 1 SYSTEMPATH/Database/BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `email` = :email:
 LIMIT 1', [...], false)
 3 SYSTEMPATH/Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(714): CodeIgniter\Model->doFirst()
 5 APPPATH/Controllers/AuthReg.php(204): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\AuthReg->processInvoice()
 7 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthReg))
 8 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH/Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-08-12 20:20:36 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'learnxac_LearnXa'@'localhost' to database 'learnxac_learnxa' in /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:186
Stack trace:
#0 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(186): mysqli->real_connect('localhost', 'learnxac_LearnX...', Object(SensitiveParameterValue), 'learnxac_learnx...', 3306, '', 0)
#1 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#3 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/BaseModel.php(714): CodeIgniter\Model->doFirst()
#6 /home/learnxac/learnxa/app/Controllers/AuthReg.php(204): CodeIgniter\BaseModel->first()
#7 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(933): App\Controllers\AuthReg->processInvoice()
#8 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthReg))
#9 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 /home/learnxac/public_html/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' to database 'learnxac_learnxa' in /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:231
Stack trace:
#0 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
#2 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#4 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/BaseModel.php(714): CodeIgniter\Model->doFirst()
#5 /home/learnxac/learnxa/app/Controllers/AuthReg.php(204): CodeIgniter\BaseModel->first()
#6 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(933): App\Controllers\AuthReg->processInvoice()
#7 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthReg))
#8 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 /home/learnxac/public_html/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2024-08-12 20:20:36 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' to database 'learnxac_learnxa'
[Method: POST, Route: invoice-process]
in SYSTEMPATH/Database/BaseConnection.php on line 467.
 1 SYSTEMPATH/Database/BaseConnection.php(614): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1637): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `email` = :email:
 LIMIT 1', [...], false)
 3 SYSTEMPATH/Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/BaseModel.php(714): CodeIgniter\Model->doFirst()
 5 APPPATH/Controllers/AuthReg.php(204): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\AuthReg->processInvoice()
 7 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthReg))
 8 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH/Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-08-12 20:28:42 --> Email: sendWithSmtp throwed ErrorException: fsockopen(): Unable to connect to ssl://smtp.gmail.com:465 (Network is unreachable) in /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Email/Email.php:1896
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'fsockopen(): Un...', '/home/learnxac/...', 1896)
#1 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Email/Email.php(1896): fsockopen('ssl://smtp.gmai...', 465, NULL, NULL, 60)
#2 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Email/Email.php(1809): CodeIgniter\Email\Email->SMTPConnect()
#3 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Email/Email.php(1694): CodeIgniter\Email\Email->sendWithSmtp()
#4 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Email/Email.php(1589): CodeIgniter\Email\Email->spoolEmail()
#5 /home/learnxac/learnxa/app/Controllers/PaymentController.php(127): CodeIgniter\Email\Email->send()
#6 /home/learnxac/learnxa/app/Controllers/PaymentController.php(88): App\Controllers\PaymentController->sendConfirmationEmail(Array)
#7 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(933): App\Controllers\PaymentController->verifyPayment()
#8 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PaymentController))
#9 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 /home/learnxac/public_html/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
ERROR - 2024-08-12 20:28:42 --> Email: Unable to send email using SMTP. Your server might not be configured to send mail using this method.
ERROR - 2024-08-12 20:28:42 --> 
ERROR - 2024-08-12 20:28:42 --> Failed to send registration confirmation email to asdf@gg.com. Error: Unable to send email using SMTP. Your server might not be configured to send mail using this method.<br><pre>Date: Mon, 12 Aug 2024 20:28:41 +0000
From: &quot;LearnXa&quot; &lt;elearnxa@gmail.com&gt;
Return-Path: &lt;elearnxa@gmail.com&gt;
To: asdf@gg.com
Subject: =?UTF-8?Q?LearnXa=20Registration=20Confirmation?=
Reply-To: &lt;elearnxa@gmail.com&gt;
User-Agent: CodeIgniter
X-Sender: elearnxa@gmail.com
X-Mailer: CodeIgniter
X-Priority: 3 (Normal)
Message-ID: &lt;66ba70797c4463.66696650@gmail.com&gt;
Mime-Version: 1.0

</pre>
ERROR - 2024-08-12 20:28:43 --> Email: sendWithSmtp throwed ErrorException: fsockopen(): Unable to connect to ssl://smtp.gmail.com:465 (Network is unreachable) in /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Email/Email.php:1896
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'fsockopen(): Un...', '/home/learnxac/...', 1896)
#1 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Email/Email.php(1896): fsockopen('ssl://smtp.gmai...', 465, NULL, NULL, 60)
#2 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Email/Email.php(1809): CodeIgniter\Email\Email->SMTPConnect()
#3 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Email/Email.php(1694): CodeIgniter\Email\Email->sendWithSmtp()
#4 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Email/Email.php(1589): CodeIgniter\Email\Email->spoolEmail()
#5 /home/learnxac/learnxa/app/Controllers/PaymentController.php(148): CodeIgniter\Email\Email->send()
#6 /home/learnxac/learnxa/app/Controllers/PaymentController.php(89): App\Controllers\PaymentController->sendDefaultPasswordEmail('asdf@gg.com', '')
#7 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(933): App\Controllers\PaymentController->verifyPayment()
#8 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PaymentController))
#9 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 /home/learnxac/public_html/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
ERROR - 2024-08-12 20:28:43 --> Email: Unable to send email using SMTP. Your server might not be configured to send mail using this method.
ERROR - 2024-08-12 20:28:43 --> Unable to send email using SMTP. Your server might not be configured to send mail using this method.
ERROR - 2024-08-12 20:28:43 --> Failed to send default password email to asdf@gg.com. Error: Unable to send email using SMTP. Your server might not be configured to send mail using this method.<br>Unable to send email using SMTP. Your server might not be configured to send mail using this method.<br><pre>Date: Mon, 12 Aug 2024 20:28:41 +0000
From: &quot;LearnXa&quot; &lt;elearnxa@gmail.com&gt;
Return-Path: &lt;elearnxa@gmail.com&gt;
To: asdf@gg.com
Subject: =?UTF-8?Q?LearnXa=20Registration=20-=20Your=20Password?=
Reply-To: &lt;elearnxa@gmail.com&gt;
User-Agent: CodeIgniter
X-Sender: elearnxa@gmail.com
X-Mailer: CodeIgniter
X-Priority: 3 (Normal)
Message-ID: &lt;66ba707a96e8b4.34547676@gmail.com&gt;
Mime-Version: 1.0

</pre>
ERROR - 2024-08-12 21:19:53 --> mysqli_sql_exception: Column 'user_id' cannot be null in /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:310
Stack trace:
#0 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(310): mysqli->query('INSERT INTO `co...', 0)
#1 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(2333): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Model.php(802): CodeIgniter\BaseModel->insert(Array, true)
#7 /home/learnxac/learnxa/app/Controllers/PaymentController.php(320): CodeIgniter\Model->insert(Array)
#8 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(933): App\Controllers\PaymentController->verifyEnrollmentPayment()
#9 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PaymentController))
#10 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 /home/learnxac/learnxa/vendor/codeigniter4/framework/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 /home/learnxac/public_html/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}
CRITICAL - 2024-08-12 21:19:53 --> CodeIgniter\Database\Exceptions\DatabaseException: Column 'user_id' cannot be null
[Method: GET, Route: verifyCourseEnrollmentPayment]
in SYSTEMPATH/Database/BaseConnection.php on line 686.
 1 SYSTEMPATH/Database/BaseBuilder.php(2333): CodeIgniter\Database\BaseConnection->query('INSERT INTO `course_enrollments` (`user_id`, `course_id`, `enrollment_date`, `price`, `status`, `payment_reference`, `payment_status`, `created_at`, `updated_at`) VALUES (:user_id:, :course_id:, :enrollment_date:, :price:, :status:, :payment_reference:, :payment_status:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH/Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH/Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH/Controllers/PaymentController.php(320): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\PaymentController->verifyEnrollmentPayment()
 7 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PaymentController))
 8 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH/Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-08-12 21:19:53 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Column 'user_id' cannot be null
in SYSTEMPATH/Database/MySQLi/Connection.php on line 315.
 1 SYSTEMPATH/Database/BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `course_enrollments` (`user_id`, `course_id`, `enrollment_date`, `price`, `status`, `payment_reference`, `payment_status`, `created_at`, `updated_at`) VALUES (NULL, \'43\', \'2024-08-12 21:19:53\', 4000, \'enrolled\', \'trx_66ba7c21679ba\', \'paid\', \'2024-08-12 21:19:53\', \'2024-08-12 21:19:53\')')
 2 SYSTEMPATH/Database/BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `course_enrollments` (`user_id`, `course_id`, `enrollment_date`, `price`, `status`, `payment_reference`, `payment_status`, `created_at`, `updated_at`) VALUES (NULL, \'43\', \'2024-08-12 21:19:53\', 4000, \'enrolled\', \'trx_66ba7c21679ba\', \'paid\', \'2024-08-12 21:19:53\', \'2024-08-12 21:19:53\')')
 3 SYSTEMPATH/Database/BaseBuilder.php(2333): CodeIgniter\Database\BaseConnection->query('INSERT INTO `course_enrollments` (`user_id`, `course_id`, `enrollment_date`, `price`, `status`, `payment_reference`, `payment_status`, `created_at`, `updated_at`) VALUES (:user_id:, :course_id:, :enrollment_date:, :price:, :status:, :payment_reference:, :payment_status:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH/Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH/Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH/Controllers/PaymentController.php(320): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\PaymentController->verifyEnrollmentPayment()
 9 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PaymentController))
10 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH/Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-08-12 21:19:53 --> [Caused by] mysqli_sql_exception: Column 'user_id' cannot be null
in SYSTEMPATH/Database/MySQLi/Connection.php on line 310.
 1 SYSTEMPATH/Database/MySQLi/Connection.php(310): mysqli->query('INSERT INTO `course_enrollments` (`user_id`, `course_id`, `enrollment_date`, `price`, `status`, `payment_reference`, `payment_status`, `created_at`, `updated_at`) VALUES (NULL, \'43\', \'2024-08-12 21:19:53\', 4000, \'enrolled\', \'trx_66ba7c21679ba\', \'paid\', \'2024-08-12 21:19:53\', \'2024-08-12 21:19:53\')', 0)
 2 SYSTEMPATH/Database/BaseConnection.php(732): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `course_enrollments` (`user_id`, `course_id`, `enrollment_date`, `price`, `status`, `payment_reference`, `payment_status`, `created_at`, `updated_at`) VALUES (NULL, \'43\', \'2024-08-12 21:19:53\', 4000, \'enrolled\', \'trx_66ba7c21679ba\', \'paid\', \'2024-08-12 21:19:53\', \'2024-08-12 21:19:53\')')
 3 SYSTEMPATH/Database/BaseConnection.php(646): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `course_enrollments` (`user_id`, `course_id`, `enrollment_date`, `price`, `status`, `payment_reference`, `payment_status`, `created_at`, `updated_at`) VALUES (NULL, \'43\', \'2024-08-12 21:19:53\', 4000, \'enrolled\', \'trx_66ba7c21679ba\', \'paid\', \'2024-08-12 21:19:53\', \'2024-08-12 21:19:53\')')
 4 SYSTEMPATH/Database/BaseBuilder.php(2333): CodeIgniter\Database\BaseConnection->query('INSERT INTO `course_enrollments` (`user_id`, `course_id`, `enrollment_date`, `price`, `status`, `payment_reference`, `payment_status`, `created_at`, `updated_at`) VALUES (:user_id:, :course_id:, :enrollment_date:, :price:, :status:, :payment_reference:, :payment_status:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH/Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH/BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH/Model.php(802): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH/Controllers/PaymentController.php(320): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\PaymentController->verifyEnrollmentPayment()
10 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PaymentController))
11 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH/Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH/index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
